---
- name: configuration of httpd in client servers
  hosts: all
  tasks:
  - name: httpd install using yum
    yum:
     name: httpd
     state: latest
  - name: start service of httpd
    service:
     name: httpd
     state: started
  - name: create a file index.html
    file:
     path: /var/www/html/index.html
     state: touch
  - name: content insert into index.html
    copy:
     content: 'Welcome to Test-Website'
     dest: /var/www/html/index.html
  - name: restart httpd
    service:
     name: httpd
     state: restarted
...
